# Merge Pull Request Apply pipeline
# Once Pull request is Merged, Starts with Follow-up Comment on PR Pipeline then applies Terraform Plan.
variables:
- group: state-data
- name: provider
  value: 'azurerm'
- name: directory
  value: 'terraform/environments/$(environment_name)' # environment_name variable is defined in pipeline
- name: plan-artifact-name
  value: 'PlanFile'
- name: plan-artifact-publish-location
  value: 'pipeline'
- name: pr-plan-pipeline-definition
  value: $(pr_plan_definition)
- name: deploy-tf-file
  value: 'deploy.tfplan'
- name: details-text-file
  value: 'pipeline-details.txt'
- name: comment-json-file
  value: 'pipeline-follow-up-comment.json'

trigger:
  branches:
    include:
    - main # Override trigger from Pipeline settings

pool:
  name: '$(environment_name)-motte-pipeline' #configure pool.
  demands:
    - ImageOverride -equals az-pipeline

stages:
- stage: Apply
  displayName: Apply Terraform Plan from pipeline artefact
  jobs:
  - job: Comment
    dependsOn: Apply
    steps:

    - template: export-pr-id.yml




    - template: build-apply-comment-as-file.yml
      parameters:
        inputFile: "$(Build.SourcesDirectory)/$(directory)/$(details-text-file)"
        outputFile: "$(Build.SourcesDirectory)/$(directory)/$(comment-json-file)"
        buildId: "$(Build.BuildId)"

    - template: ../steps/az-cli-post-pr-comment.yml
      parameters:
        PR_ID: $(OriginalPullRequestId)
        comment_json_file: $(comment-json-file)

  - job: Apply
    steps:
      
    - task: DownloadPipelineArtifact@2
      displayName: Download Plan file artifact
      inputs:
        source: 'specific'
        project: $(System.TeamProjectId)
        definition:  $(pr-plan-pipeline-definition)
        artifact: $(plan-artifact-name)
        buildVersionToDownload: latest
        targetPath: $(Build.SourcesDirectory)/$(directory)

    - template: ../steps/git-config-pat.yml
      
    - template: ../steps/terraform-init.yml

    - task: TerraformTaskV4@4
      displayName: Terraform Apply
      inputs:
        provider: $(provider)
        command: 'apply'
        workingDirectory: $(directory)
        commandOptions: '$(Build.SourcesDirectory)/$(directory)/$(deploy-tf-file)'
        environmentServiceNameAzureRM: $(service-connection)
      env:
        ARM_USE_AZUREAD: true
        ARM_USE_OIDC: true
        TF_INPUT: 0
        TF_LOG: DEBUG
        
    - template: ../steps/git-config-reset.yml